### ISSUE TITLE
Model usage issues

### ISSUE THREAD

**Issue by sukeey** [michelecafagna26/CLIPCap#1]
Hello author, thank you very much for your work. 

I used your fine-tuned model to generate captions, but there were many repeated sentences in the result, as shown in the picture below. I don’t know if this happened during your fine-tuning process.Not sure if it's because some of the pictures have a lot of text on them

In addition, how effective is your fine-tuning process? I want to use your repo to generate the captions of some pictures as auxiliary information for the model. I don’t know whether the overall accuracy or effect of your fine-tuned model can be used as a tool.

Thank you again for your work and I look forward to hearing from you！

![微信图片_20240118101239](https://github.com/michelecafagna26/CLIPCap/assets/50063094/554f5404-41ef-4953-b98e-6d1356ac4e90)
![07](https://github.com/michelecafagna26/CLIPCap/assets/50063094/f267a11f-878b-4de4-b591-fa4e346a8445)

**Comment by michelecafagna26** [comment]
Hi! and  thanks for your interest in this repo.

Which model are you using? Actions?

I see, you're right, I noticed this phenomenon when you try to caption out-of-distribution images. So the model tends to either hallucinate something it is familiar with (in terms of similarity with fine-tuned data) or keeps repeating itself.

Consider two things: 

1) the model is a baseline so the fine-tuning wasn't extremely optimized (however I don't think this is the problem here). 
2) ClipCap uses a simple mapping layer to learn a prefix. When you fine-tune you have two options:

          - Fine-tuning only the mapping network

          - Jointly fine-tune the mapping network and the LM.

I've optimized only the mapping network, as it was sufficient for my use case, so it makes sense that it's not so robust with "unfamiliar" images.

I can suggest you to do a short fine-tuning with your data, or to fine-tune the LM+mapping network. You can use the original repo for that.

If you don't have any constraint regarding the captioning model, you can try other baselines that I've trained on the same tasks.
you can find them on  [huggingface](https://huggingface.co/michelecafagna26)

I hope I was helpful!

**Comment by sukeey** [comment]
Thank you very much for your reply! I will try other baselines you posted on huggingface for the same task, thanks again for your work!

**Comment by michelecafagna26** [comment]
You're welcome!
I'm gonna close this issue then.
